# Generated by Django 6.0.2 on 2026-02-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('diseases', models.TextField()),
                ('image', models.ImageField(upload_to='herbs/')),
                ('model_3d_url', models.URLField()),
            ],
        ),
    ]
